### PR TITLE
Fixed issue with reading files that are over 2GB

### PR DESCRIPTION
**Pull request by KantorFitz**
Fixes the issue #25

### CODE REVIEW

**Comment by GewoonJaap** [comment]
Hi @KantorFitz 
Thanks for your PR. I didn't have time this weekend to look at it. The code changes look good but I will compile and test it when I am home today.

**Comment by KantorFitz** [comment]
> Hi @KantorFitz 
> Thanks for your PR. I didn't have time this weekend to look at it. The code changes look good but I will compile and test it when I am home today.

Sure, btw sorry for that second commit which is not strictly related to the main problem. Just say if it should be moved to separate PR and I will prepare one.

**Comment by GewoonJaap** [comment]
Ah that's fine, just keep it like this :D. It ain't a big change

**Comment by GewoonJaap** [comment]
Thanks for the PR, I just tested it and it works good! :)

**Pull request merged**
